### ISSUE TITLE
How to get dep_gold_vocab.txt?

### ISSUE THREAD

**Issue by sophiayyya** [Fantabulous-J/coref-HGAT#1]
Hi,

Thanks for your great code! When I run your code, I encountered a problem. "dep_gold_vocab.txt" and "pos_tag_vocab.txt" are missed and I don't know how to generate the two files. Could please upload these files or scripts of generating these files?

Thanks in advance.

**Comment by Fantabulous-J** [comment]
Thanks for your interest in our paper! I have uploaded these two files, please check! 
Please let me know if you have additional questions.

**Comment by sophiayyya** [comment]
Got it! Thank you for your quick reply.
