### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Twim17** [Fantabulous-J/coref-HGAT#3]

**Comment by Twim17** [comment]
Hi. I followed the instructions on the readme but I encountered some problems:

- Setup: it seems that the requirements have some conflicts between them (`tensorflow_gpu==1.15.0` depends on `gast==0.2.2` while `tensorflow==2.3.1` depends on `gast==0.3.3`, to solve this I installed `tensorflow==1.15`. `scikit_learn==0.23.2` does not have `sklearn.utils.linear_assignment_` which is deprecated so I installed `scikit_learn==0.22.2`)
- Build Kernel:
no problems in this step
- Training:
when I use the command  `python train.py train_spanbert_base_hgat_dep_srl_two_way` I get the following print and error:

> Using backend: pytorch
> /mypath/anaconda3/envs/envNUANS/lib/python3.7/site-packages/sklearn/utils/linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
>   FutureWarning)
> Running experiment: train_spanbert_base_hgat_dep_srl_two_way
> data_dir = "."
> model_type = "independent"
> max_num_candidates = 3900
> max_top_antecedents = 50
> max_training_sentences = 3
> top_span_ratio = 0.4
> max_num_speakers = 20
> max_segment_len = 384
> bert_learning_rate = 2e-05
> task_learning_rate = 0.0003
> num_docs = 2802
> dropout_rate = 0.3
> ffnn_size = 3000
> ffnn_depth = 1
> num_epochs = 40
> feature_size = 20
> max_span_width = 30
> use_metadata = true
> use_features = true
> use_segment_distance = true
> model_heads = true
> coref_depth = 2
> coarse_to_fine = true
> fine_grained = true
> use_prior = true
> train_path = "conll_data/train.english.384.jsonlines"
> eval_path = "conll_data/dev.english.384.jsonlines"
> conll_eval_path = "dev.english.v4_gold_conll"
> single_example = true
> genres = [
>   "bc"
>   "bn"
>   "mz"
>   "nw"
>   "pt"
>   "tc"
>   "wb"
> ]
> eval_frequency = 1000
> report_frequency = 100
> log_root = "."
> adam_eps = 1e-06
> task_optimizer = "adam"
> seed = 2333
> hidden_size = 768
> mention_loss = true
> mention_loss_ratio = 0.5
> loss_start_ratio = 0.3
> loss_end_ratio = 0.3
> loss_span_ratio = 0.3
> test_path = "conll_data/test.english.384.jsonlines"
> conll_dev_path = "conll_data/dev.english.v4_gold_conll"
> conll_test_path = "conll_data/test.english.v4_gold_conll"
> bert_config_file = "spanbert_base/bert_config.json"
> vocab_file = "spanbert_base/vocab.txt"
> best_checkpoint = "train_spanbert_base_hgat_dep_srl_two_way_384/model_best.checkpoint"
> tf_checkpoint = "spanbert_base/model.max.ckpt"
> init_checkpoint_dir = "spanbert_base"
> load_from_pretrained = true
> pos_vocab_file = "conll_data/pos_tag_vocab.txt"
> dep_vocab_file = "conll_data/dep_gold_vocab.txt"
> train_dep_path = "conll_data/train.english.depparse.gold.jsonlines"
> eval_dep_path = "conll_data/dev.english.depparse.gold.jsonlines"
> test_dep_path = "conll_data/test.english.depparse.gold.jsonlines"
> dep_hidden_size = 300
> srl_hidden_size = 300
> dep_dropout_rate = 0.2
> num_iterations = 2
> num_heads = 4
> singleton = false
> log_dir = "./train_spanbert_base_hgat_dep_srl_two_way_384"
> cuda
> Some weights of BertModel were not initialized from the model checkpoint at spanbert_base and are newly initialized: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> bert parameters
> n: bert.embeddings.word_embeddings.weight, shape: torch.Size([28996, 768])
> n: bert.embeddings.position_embeddings.weight, shape: torch.Size([512, 768])
> n: bert.embeddings.token_type_embeddings.weight, shape: torch.Size([2, 768])
> n: bert.embeddings.LayerNorm.weight, shape: torch.Size([768])
> n: bert.embeddings.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.0.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.0.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.0.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.0.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.0.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.0.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.0.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.0.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.0.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.0.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.0.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.0.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.0.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.0.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.0.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.0.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.1.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.1.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.1.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.1.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.1.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.1.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.1.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.1.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.1.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.1.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.1.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.1.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.1.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.1.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.1.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.1.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.2.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.2.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.2.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.2.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.2.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.2.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.2.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.2.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.2.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.2.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.2.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.2.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.2.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.2.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.2.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.2.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.3.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.3.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.3.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.3.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.3.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.3.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.3.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.3.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.3.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.3.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.3.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.3.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.3.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.3.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.3.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.3.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.4.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.4.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.4.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.4.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.4.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.4.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.4.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.4.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.4.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.4.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.4.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.4.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.4.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.4.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.4.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.4.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.5.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.5.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.5.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.5.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.5.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.5.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.5.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.5.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.5.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.5.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.5.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.5.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.5.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.5.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.5.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.5.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.6.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.6.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.6.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.6.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.6.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.6.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.6.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.6.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.6.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.6.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.6.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.6.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.6.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.6.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.6.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.6.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.7.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.7.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.7.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.7.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.7.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.7.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.7.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.7.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.7.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.7.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.7.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.7.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.7.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.7.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.7.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.7.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.8.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.8.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.8.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.8.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.8.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.8.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.8.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.8.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.8.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.8.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.8.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.8.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.8.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.8.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.8.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.8.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.9.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.9.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.9.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.9.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.9.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.9.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.9.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.9.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.9.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.9.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.9.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.9.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.9.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.9.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.9.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.9.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.10.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.10.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.10.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.10.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.10.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.10.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.10.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.10.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.10.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.10.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.10.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.10.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.10.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.10.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.10.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.10.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.11.attention.self.query.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.11.attention.self.query.bias, shape: torch.Size([768])
> n: bert.encoder.layer.11.attention.self.key.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.11.attention.self.key.bias, shape: torch.Size([768])
> n: bert.encoder.layer.11.attention.self.value.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.11.attention.self.value.bias, shape: torch.Size([768])
> n: bert.encoder.layer.11.attention.output.dense.weight, shape: torch.Size([768, 768])
> n: bert.encoder.layer.11.attention.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.11.attention.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.11.attention.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.encoder.layer.11.intermediate.dense.weight, shape: torch.Size([3072, 768])
> n: bert.encoder.layer.11.intermediate.dense.bias, shape: torch.Size([3072])
> n: bert.encoder.layer.11.output.dense.weight, shape: torch.Size([768, 3072])
> n: bert.encoder.layer.11.output.dense.bias, shape: torch.Size([768])
> n: bert.encoder.layer.11.output.LayerNorm.weight, shape: torch.Size([768])
> n: bert.encoder.layer.11.output.LayerNorm.bias, shape: torch.Size([768])
> n: bert.pooler.dense.weight, shape: torch.Size([768, 768])
> n: bert.pooler.dense.bias, shape: torch.Size([768])
> ******************************************************************************************************************************************************
> task parameters
> n: span_width_embeddings.weight, shape: torch.Size([30, 20])
> n: span_width_prior_embeddings.weight, shape: torch.Size([30, 20])
> n: genre_embeddings.weight, shape: torch.Size([7, 20])
> n: antecedent_distance_embeddings.weight, shape: torch.Size([10, 20])
> n: antecedent_distance_embeddings_coref_layer.weight, shape: torch.Size([10, 20])
> n: same_speaker_embeddings.weight, shape: torch.Size([2, 20])
> n: dep_edge_embeddings.weight, shape: torch.Size([46, 300])
> n: srl_edge_embeddings.weight, shape: torch.Size([67, 300])
> n: segment_distance_embeddings.weight, shape: torch.Size([3, 20])
> n: mention_word_attn_layer.output_layer.weight, shape: torch.Size([1, 768])
> n: mention_word_attn_layer.output_layer.bias, shape: torch.Size([1])
> n: mention_score_layer.hidden_layer_0.weight, shape: torch.Size([3000, 2324])
> n: mention_score_layer.hidden_layer_0.bias, shape: torch.Size([3000])
> n: mention_score_layer.output_layer.weight, shape: torch.Size([1, 3000])
> n: mention_score_layer.output_layer.bias, shape: torch.Size([1])
> n: width_scores_layer.hidden_layer_0.weight, shape: torch.Size([3000, 20])
> n: width_scores_layer.hidden_layer_0.bias, shape: torch.Size([3000])
> n: width_scores_layer.output_layer.weight, shape: torch.Size([1, 3000])
> n: width_scores_layer.output_layer.bias, shape: torch.Size([1])
> n: src_projection.output_layer.weight, shape: torch.Size([2324, 2324])
> n: src_projection.output_layer.bias, shape: torch.Size([2324])
> n: antecedent_distance_scores_projection.output_layer.weight, shape: torch.Size([1, 20])
> n: antecedent_distance_scores_projection.output_layer.bias, shape: torch.Size([1])
> n: slow_antecedent_scores_layer.hidden_layer_0.weight, shape: torch.Size([3000, 7052])
> n: slow_antecedent_scores_layer.hidden_layer_0.bias, shape: torch.Size([3000])
> n: slow_antecedent_scores_layer.output_layer.weight, shape: torch.Size([1, 3000])
> n: slow_antecedent_scores_layer.output_layer.bias, shape: torch.Size([1])
> n: tt_gat_layer.layer.fc.weight, shape: torch.Size([768, 768])
> n: tt_gat_layer.layer.feat_fc.weight, shape: torch.Size([768, 300])
> n: tt_gat_layer.layer.attn_fc.weight, shape: torch.Size([1, 576])
> n: ta_gat_layer.layer.fc.weight, shape: torch.Size([768, 768])
> n: ta_gat_layer.layer.attn_fc.weight, shape: torch.Size([1, 384])
> n: ap_gat_layer.layer.fc.weight, shape: torch.Size([768, 768])
> n: ap_gat_layer.layer.feat_fc.weight, shape: torch.Size([768, 300])
> n: ap_gat_layer.layer.attn_fc.weight, shape: torch.Size([1, 576])
> n: pa_gat_layer.layer.fc.weight, shape: torch.Size([768, 768])
> n: pa_gat_layer.layer.feat_fc.weight, shape: torch.Size([768, 300])
> n: pa_gat_layer.layer.attn_fc.weight, shape: torch.Size([1, 576])
> n: at_gat_layer.layer.fc.weight, shape: torch.Size([768, 768])
> n: at_gat_layer.layer.attn_fc.weight, shape: torch.Size([1, 384])
> n: fusion_gate.output_layer.weight, shape: torch.Size([768, 1536])
> n: fusion_gate.output_layer.bias, shape: torch.Size([768])
> n: linear_dep.output_layer.weight, shape: torch.Size([1, 1536])
> n: linear_dep.output_layer.bias, shape: torch.Size([1])
> n: linear_srl.output_layer.weight, shape: torch.Size([1, 1536])
> n: linear_srl.output_layer.bias, shape: torch.Size([1])
> Total parameters: 146782411
> 2023-01-22 20:19:43,700 - INFO - __main__ - =*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*==*=
> 2023-01-22 20:19:43,700 - INFO - __main__ - start 0 Epoch ... 
> Traceback (most recent call last):
>   File "train.py", line 191, in <module>
>     train()
>   File "train.py", line 84, in train
>     for i, batch in enumerate(train_dataloader):
>   File "/mypath/anaconda3/envs/envNUANS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
>     data = self._next_data()
>   File "/mypath/anaconda3/envs/envNUANS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
>     return self._process_data(data)
>   File "/mypath/anaconda3/envs/envNUANS/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
>     data.reraise()
>   File "/mypath/anaconda3/envs/envNUANS/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
>     raise self.exc_type(msg)
> IndexError: Caught IndexError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/mypath/anaconda3/envs/envNUANS/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/mypath/anaconda3/envs/envNUANS/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/mypath/anaconda3/envs/envNUANS/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/mypath/Desktop/NUANS/coref-HGAT-main/conll_dataloader.py", line 51, in __getitem__
>     example = self.create_graph(*example, self.dependencies[item])
> IndexError: list index out of range
> 

What should I do? I'm quite sure that the `setup_training.sh` created the right files, but if I should check something in particular let me know.
P.S. this is the first issue I posted on GitHub so if I should change something just let me know.

EDIT:
The parser created the wrong files. I corrected them and now is going fine

**Comment by hieutran-coder** [comment]
Traceback (most recent call last):
  File "/Users/mac/Documents/Google_Drive_1/Đo_an_20222/Week11/coref-HGAT-main/train.py", line 191, in <module>
    train()
  File "/Users/mac/Documents/Google_Drive_1/Đo_an_20222/Week11/coref-HGAT-main/train.py", line 84, in train
    for i, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/mac/Documents/Google_Drive_1/Đo_an_20222/Week11/coref-HGAT-main/conll_dataloader.py", line 52, in __getitem__
    raise IndexError("Dependencies list index out of range.")
IndexError: Dependencies list index out of range.


Hi, Twim17, I have the same problem as you, hic :(
**The parser created the wrong files. I corrected them and now is going fine**
 Could you tell me how to correct the parser? Thanks!
Sincerely,
HieuTran

**Comment by Twim17** [comment]
Hi, I'm really sorry but I forgot what I did. I just remember it had something to do with the files in the `/conll_data/conll-2012/v3/scripts` directory.

**Comment by hieutran-coder** [comment]
Thank you for reply,
This project holds great significance to me as I choose coreference resolution as the focus of my graduation project in Computer science. But I have limited experience with coding. Could you  please assist me in running this code or this script  , Do you still keep your fix of this script, hic?
<img width="221" alt="Screen Shot 2023-06-06 at 14 17 58" src="https://github.com/Fantabulous-J/coref-HGAT/assets/57060034/009d73fe-1f43-4ef8-9d31-14ec508cdaaf">

Hopefully, you can take a little time to help me. I am really grateful if you help :) 🙏

**Comment by hieutran-coder** [comment]
Oh, I have solved this!!. It is the **mismatch number of rows** between **dev.english.384.jsonlines** file with **dev.dependency.depparse file** because I ran the data preprocessor many times, it resulted in it inserting new preprocessed data into the file **dev.english.384.jsonlines**
